export const REQUEST_LOADING_FILMS = 'REQUEST_LOADING_FILMS';
export const REQUEST_SUCESS_FILMS = 'REQUEST_SUCESS_FILMS';
export const REQUEST_FAILURE_FILMS = 'REQUEST_FAILURE_FILMS';

export const REQUEST_LOADING_PEOPLE = 'REQUEST_LOADING_PEOPLE';
export const REQUEST_SUCESS_PEOPLE = 'REQUEST_SUCESS_PEOPLE';
export const REQUEST_FAILURE_PEOPLE = 'REQUEST_FAILURE_PEOPLE';

export const REQUEST_SUCESS_FILM = 'REQUEST_SUCESS_FILM';
export const REQUEST_LOADING_FILM = 'REQUEST_LOADING_FILM';
export const REQUEST_FAILURE_FILM = 'REQUEST_FAILURE_FILM';
