export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUEST_SUCESS_FILMS = 'REQUEST_SUCESS_FILMS';
export const REQUEST_SUCESS_PEOPLE = 'REQUEST_SUCESS_PEOPLE';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';